version: '3'
services:
  mongouserdatabase:
    container_name: mongouserdatabase
    restart: always
    build: .
    ports:
    - "4000:4000"
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ./app/src/app
    ports:
      - '27018:27017'

    
   
    